### ISSUE TITLE
Issue with appearance

### ISSUE THREAD

**Issue by eaugust** [ahmedlhanafy/Ubuntu-Ui-Theme-for-Nylas-N1#1]
I just installed the Ubuntu theme and it doesn't look like your screenshot.  I'm running the latest version of N1 (0.3.45) for Windows 7.  The top section is white and the icons are only (barely) visible once you hover over them with the mouse. Is there anything else I need to do other than install the theme via the Preferences/General screen.  See attached screenshots.
![preferences](https://cloud.githubusercontent.com/assets/10822498/12786447/28a8e470-ca5f-11e5-8f16-f64ee134e2cd.png)
![inbox](https://cloud.githubusercontent.com/assets/10822498/12786451/2e833f62-ca5f-11e5-96f6-34bd1862a4fe.png)

**Comment by ahmedlhanafy** [comment]
#2 duplicate
