### ISSUE TITLE
Ubuntu-Ui-Theme -  uncolored

### ISSUE THREAD

**Issue by cristianfb1989** [ahmedlhanafy/Ubuntu-Ui-Theme-for-Nylas-N1#2]
Hello there! I have a little trouble with Ubuntu-Ui-Theme-for-Nylas-N1. No colored icons appear when you select one or more mails. 
![ubuntu](https://cloud.githubusercontent.com/assets/16965222/12876853/4d5e4d42-cde7-11e5-8ee3-d61b99dd0f49.PNG)

How should I set the code to the theme look like the main screenshot?

Thx!

**Comment by ahmedlhanafy** [comment]
It's meant to be used with Ubutnu Linux but I will revamp the whole theme in the coming days so stay tuned

**Comment by cristianfb1989** [comment]
Perfect!!!!

**Comment by ahmedlhanafy** [comment]
Try the new version with Windows and let me know if your problem is fixed.

**Comment by cristianfb1989** [comment]
alright!

**Comment by ahmedlhanafy** [comment]
Does the last update solve your problem?

**Comment by cristianfb1989** [comment]
Yes, that was resolved.
