### ISSUE TITLE
"<parent directory>" label barely visible

### ISSUE THREAD

**Issue by itsabdelrahman** [ahmedlhanafy/Ubuntu-Ui-Theme-for-Nylas-N1#5]
Lovely theme!

Just one little, tiny thing: in single panel layout, the <parent directory> label (whose tooltip is "Return to parent directory") on the top left isn't quite visible - which in this layout mode is a bit important.

![screenshot from 2016-03-04 15 49 39](https://cloud.githubusercontent.com/assets/11808903/13528747/c23c14a8-e220-11e5-8d72-ed36d3501064.png)
(in the screenshot, it's the "All Mail" label)

Thanks a lot again for the amazing theme!

**Comment by ahmedlhanafy** [comment]
I will fix it in the next release.

**Comment by ahmedlhanafy** [comment]
It's now fixed
